version: '3'
services:
#  nginx:
#    image: nginx
#    volumes:
#      - ../../conf/nginx/nginx.prod.conf:/etc/nginx/nginx.conf
#      - ../../conf/nginx/api.safeu.a2os.club:/etc/nginx/sites-enabled/api.safeu.a2os.club
#      - /etc/letsencrypt/live/api.safeu.a2os.club:/opt/nginx/api.safeu.a2os.club/
#    environment:
#      - TZ=Asia/Shanghai
#    ports:
#      - "80:80"
#    networks:
#      - lbnet
#    depends_on:
#      - web1
#      - web2
#    restart: on-failure

  safeu1:
    build:
      context: ../..
      dockerfile: ././build/package/safeu-backend/Dockerfile-compose
    volumes:
      - ../../log/safeu1:/go/src/a2os/safeu-backend/log
      # - ../..:/go/src/a2os/safeu-backend/
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "8090:8080"
    networks:
      - safeu-app-net
    depends_on:
      - safeu-redis
    restart: on-failure

  safeu2:
    build:
      context: ../..
      dockerfile: ././build/package/safeu-backend/Dockerfile-compose
    volumes:
      - ../../log/safeu2:/go/src/a2os/safeu-backend/log
      # - ../..:/go/src/a2os/safeu-backend/
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "8091:8080"
    networks:
      - safeu-app-net
    depends_on:
      - safeu-redis
    restart: on-failure

  safeu3:
    build:
      context: ../..
      dockerfile: ././build/package/safeu-backend/Dockerfile-compose
    volumes:
      - ../../log/safeu3:/go/src/a2os/safeu-backend/log
      # - ../..:/go/src/a2os/safeu-backend/
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "8092:8080"
    networks:
      - safeu-app-net
    depends_on:
      - safeu-redis
    restart: on-failure

#  db:
#    environment:
#      - TZ=Asia/Shanghai
#      - MYSQL_ROOT_PASSWORD=safeu
#      - MYSQL_DATABASE=safeu
#    image: mariadb:10.3
#    volumes:
#      - ../../data/mariadb:/var/lib/mysql
#      - ../../conf/mariadb:/etc/mysql/conf.d
#    ports:
#      - "3306:3306"
#    networks:
#      - dbnet
#    restart: on-failure
  safeu-redis:
    image: redis:5.0.3-alpine
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ../../conf/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ../../data/redis:/data # for redis persistent storage
    entrypoint: redis-server /usr/local/etc/redis/redis.conf
    # no reveal for ports, waiting for the database instance
    # ports:
    #   - "6379:6379"
    networks:
      - safeu-app-net
    restart: on-failure

networks:
  safeu-app-net:
