version: '3'
services:
  web:
    build:
      context: ../..
      dockerfile: ././build/package/safeu-backend-dev/Dockerfile-compose
    volumes:
#      - ../..:/go/src/a2os/safeu-backend/
      - ../../log/web:/go/src/a2os/safeu-backend/log/
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "8080:8080"
    networks:
      - webnet
    depends_on:
      - db
      - redis
    restart: always
  db:
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=safeu
      - MYSQL_DATABASE=safeu
    image: mariadb:10.3
    volumes:
      - ../../data-dev/mariadb:/var/lib/mysql
      - ../../conf/mariadb:/etc/mysql/conf.d
    ports:
      - "3306:3306"
    networks:
      - webnet
  redis:
    image: redis:5.0.3-alpine
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ../../conf/redis/redis.conf:/usr/local/etc/redis/redis.conf
#      - ../../data-dev/redis:/data # for redis persistent storage
    entrypoint: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    networks:
      - webnet

networks:
  webnet:
