version: '3'
services:
  web:
    build:
      context: ../..
      dockerfile: ././build/package/safeu-backend-dev/Dockerfile-compose
    volumes:
      - ../..:$GOPATH/src/a2os/safeu-backend/
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "8080:8080"
    networks:
      - webnet
    depends_on:
      - db
      - redis
    restart: always
  db:
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=safeu
      - MYSQL_DATABASE=safeu
    image: mariadb:10.3
    volumes:
      - ../../db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - webnet
  redis:
    image: redis:5.0.3-alpine
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "6379:6379"
    networks:
      - webnet

networks:
  webnet:
