version: '3'
services:
  web:
    build:
      context: ../../..
      dockerfile: ../../../build/package/safeu-backend-dev/Dockerfile
    volumes:
      - ../../..:$GOPATH/src/a2os/safeu-backend/
    ports:
      - "8080:8080"
    networks:
      - webnet
  db:
    environment:
      - MYSQL_ROOT_PASSWORD=safeu
      - MYSQL_DATABASE=safeu
    image: mariadb
    ports:
      - "3306:3306"
    networks:
      - webnet

networks:
  webnet:
